name: Generalized Alpha CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: dealii/dealii:v9.4.0-focal
      options: --user root

    steps:
    - uses: actions/checkout@v2

    - name: Create build directory
      run: mkdir -p Computation@Scale/Generalized_alpha_NS_1D/build

    - name: Configure CMake
      working-directory: Computation@Scale/Generalized_alpha_NS_1D/build
      run: cmake ..

    - name: Build
      working-directory: Computation@Scale/Generalized_alpha_NS_1D/build
      run: make -j${NPROC}

    - name: Run tests
      working-directory: Computation@Scale/Generalized_alpha_NS_1D/build
      run: ctest --output-on-failure
