name: Manufactured solver test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: dealii/dealii:master-focal
      options: --user root
    steps:
    - uses: actions/checkout@v2
    
    - name: Update packages
      run: |
        apt-get update
        apt-get install -yq valgrind libomp-dev
        
    - name: Install Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        git checkout v3.4.0
        cmake -B build .
        cmake --build build --target install
        cd ..
        
    - name: Configure
      working-directory: ./Computation@Scale
      run: |
        mkdir -p build
        cd build
        cmake ..
        
    - name: Build and test
      working-directory: ./Computation@Scale/build
      run: |
        make -j$(nproc)
        ./manufactured_test
